### ISSUE TITLE
Great Expectations Fail

### ISSUE THREAD

**Issue by tbabin02** [PrefectHQ/prefect-great-expectations#29]
This isn't necessarily a bug. But in Validation.py. Line 136. If Great Expectations fail it would be preferable not to raise an error and have the whole prefect flow fail. It would be better just to warn that it failed and comment out the raising_on_validation_failure. So that I know the flow is fine but I can print out some results. 

```

if not result.success:
        logger.warn(
            "Great Expectations validation run %s failed", result.run_id.run_name
        )
        if raise_on_validation_failure:
            raise GreatExpectationValidationError(result)
    else:
        logger.info(
            "Great Expectations validation run %s succeeded", result.run_id.run_name
        )
```

**Comment by desertaxle** [comment]
Hey @tbabin02! `raise_on_validation` defaults to `True`, but you can pass in `False` so that your task doesn't raise an exception if the validation fails. It sounds like the task already supports the behavior that you're looking for, but feel free to let me know if I've misunderstood your request.

**Comment by tbabin02** [comment]
Oh thank you, nope that solves my problem! Did not notice that.
